Change password for Wazuh Linux instance for Azure deployment
Updated the password for the Wazuh Linux instance for the Azure deployment, due to password complexity rules enforced by Azure:
Error: "admin_password" has to fulfill 3 out of these 4 conditions: Has lower characters, Has upper characters, Has a digit, Has a special character other than "_", fulfilled only 1 conditions